# Generated by Django 5.2.3 on 2025-06-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='原網址')),
                ('short_code', models.CharField(max_length=20, unique=True, verbose_name='縮網址代碼')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密碼')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
